services:
  blog_strapi_api:
    container_name: blog_strapi_api
    hostname: blog_strapi_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: cesario13
      POSTGRES_DB: blog-strapi
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - /home/deojunior/.PostgreesData/postgreonly/blog_strapi_api:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
